/**
 * Granular permission catalogue.
 *
 * Access control is permission-based, never role-name-based. Roles are simply
 * named bundles of these permissions and can be reconfigured at runtime without
 * touching application code.
 */

export const PERMISSIONS = {
  TRIPS_READ: 'trips.read',
  TRIPS_CREATE: 'trips.create',
  TRIPS_UPDATE: 'trips.update',
  TRIPS_CANCEL: 'trips.cancel',

  TRAVELERS_READ: 'travelers.read',
  TRAVELERS_CREATE: 'travelers.create',
  TRAVELERS_UPDATE: 'travelers.update',
  TRAVELERS_MERGE: 'travelers.merge',

  HOTELS_READ: 'hotels.read',
  HOTELS_CREATE: 'hotels.create',
  HOTELS_UPDATE: 'hotels.update',
  HOTELS_CANCEL: 'hotels.cancel',

  TRANSFERS_READ: 'transfers.read',
  TRANSFERS_CREATE: 'transfers.create',
  TRANSFERS_UPDATE: 'transfers.update',
  TRANSFERS_ASSIGN: 'transfers.assign',
  TRANSFERS_STATUS_UPDATE: 'transfers.status.update',

  EXCURSIONS_READ: 'excursions.read',
  EXCURSIONS_CREATE: 'excursions.create',
  EXCURSIONS_UPDATE: 'excursions.update',

  VISAS_READ: 'visas.read',
  VISAS_CREATE: 'visas.create',
  VISAS_UPDATE: 'visas.update',
  VISAS_FINANCE_READ: 'visas.finance.read',

  FINANCE_READ: 'finance.read',
  FINANCE_DOCUMENTS_MANAGE: 'finance.documents.manage',
  FINANCE_PAYMENTS_CREATE: 'finance.payments.create',
  FINANCE_PAYMENTS_REVERSE: 'finance.payments.reverse',
  FINANCE_RECONCILE: 'finance.reconcile',

  IMPORTS_UPLOAD: 'imports.upload',
  IMPORTS_REVIEW: 'imports.review',
  IMPORTS_APPLY: 'imports.apply',

  DATA_QUALITY_READ: 'data_quality.read',
  DATA_QUALITY_RESOLVE: 'data_quality.resolve',

  MASTER_DATA_READ: 'master_data.read',
  MASTER_DATA_MANAGE: 'master_data.manage',

  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_MANAGE: 'users.manage',

  ROLES_MANAGE: 'roles.manage',
  AUDIT_READ: 'audit.read',
  REPORTS_EXPORT: 'reports.export',
  API_KEYS_CREATE: 'api_keys.create',
  API_KEYS_MANAGE: 'api_keys.manage',
  SETTINGS_MANAGE: 'settings.manage',
  ATTACHMENTS_READ: 'attachments.read',
  ATTACHMENTS_UPLOAD: 'attachments.upload',
  NOTIFICATIONS_READ: 'notifications.read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSIONS = Object.values(PERMISSIONS) as Permission[];

/** Grouping used by the admin UI when rendering the permission matrix. */
export const PERMISSION_GROUPS: Record<string, Permission[]> = {
  trips: [
    PERMISSIONS.TRIPS_READ,
    PERMISSIONS.TRIPS_CREATE,
    PERMISSIONS.TRIPS_UPDATE,
    PERMISSIONS.TRIPS_CANCEL,
  ],
  travelers: [
    PERMISSIONS.TRAVELERS_READ,
    PERMISSIONS.TRAVELERS_CREATE,
    PERMISSIONS.TRAVELERS_UPDATE,
    PERMISSIONS.TRAVELERS_MERGE,
  ],
  hotels: [
    PERMISSIONS.HOTELS_READ,
    PERMISSIONS.HOTELS_CREATE,
    PERMISSIONS.HOTELS_UPDATE,
    PERMISSIONS.HOTELS_CANCEL,
  ],
  transfers: [
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.TRANSFERS_CREATE,
    PERMISSIONS.TRANSFERS_UPDATE,
    PERMISSIONS.TRANSFERS_ASSIGN,
    PERMISSIONS.TRANSFERS_STATUS_UPDATE,
  ],
  excursions: [
    PERMISSIONS.EXCURSIONS_READ,
    PERMISSIONS.EXCURSIONS_CREATE,
    PERMISSIONS.EXCURSIONS_UPDATE,
  ],
  visas: [
    PERMISSIONS.VISAS_READ,
    PERMISSIONS.VISAS_CREATE,
    PERMISSIONS.VISAS_UPDATE,
    PERMISSIONS.VISAS_FINANCE_READ,
  ],
  finance: [
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_DOCUMENTS_MANAGE,
    PERMISSIONS.FINANCE_PAYMENTS_CREATE,
    PERMISSIONS.FINANCE_PAYMENTS_REVERSE,
    PERMISSIONS.FINANCE_RECONCILE,
  ],
  imports: [
    PERMISSIONS.IMPORTS_UPLOAD,
    PERMISSIONS.IMPORTS_REVIEW,
    PERMISSIONS.IMPORTS_APPLY,
  ],
  dataQuality: [PERMISSIONS.DATA_QUALITY_READ, PERMISSIONS.DATA_QUALITY_RESOLVE],
  masterData: [PERMISSIONS.MASTER_DATA_READ, PERMISSIONS.MASTER_DATA_MANAGE],
  administration: [
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.ROLES_MANAGE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.API_KEYS_CREATE,
    PERMISSIONS.API_KEYS_MANAGE,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
  other: [
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.ATTACHMENTS_UPLOAD,
    PERMISSIONS.NOTIFICATIONS_READ,
  ],
};

/** Seed roles. These are starting bundles — administrators may edit them later. */
export const SYSTEM_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  RESERVATION_AGENT: 'RESERVATION_AGENT',
  TRANSFER_COORDINATOR: 'TRANSFER_COORDINATOR',
  EXCURSION_COORDINATOR: 'EXCURSION_COORDINATOR',
  VISA_AGENT: 'VISA_AGENT',
  FINANCE: 'FINANCE',
  VIEWER: 'VIEWER',
} as const;
export type SystemRole = (typeof SYSTEM_ROLES)[keyof typeof SYSTEM_ROLES];

const READ_ONLY: Permission[] = [
  PERMISSIONS.TRIPS_READ,
  PERMISSIONS.TRAVELERS_READ,
  PERMISSIONS.HOTELS_READ,
  PERMISSIONS.TRANSFERS_READ,
  PERMISSIONS.EXCURSIONS_READ,
  PERMISSIONS.VISAS_READ,
  PERMISSIONS.MASTER_DATA_READ,
  PERMISSIONS.NOTIFICATIONS_READ,
];

export const DEFAULT_ROLE_PERMISSIONS: Record<SystemRole, Permission[]> = {
  SUPER_ADMIN: ALL_PERMISSIONS,
  ADMIN: ALL_PERMISSIONS.filter((p) => p !== PERMISSIONS.API_KEYS_MANAGE),
  OPERATIONS_MANAGER: [
    ...READ_ONLY,
    PERMISSIONS.TRIPS_CREATE,
    PERMISSIONS.TRIPS_UPDATE,
    PERMISSIONS.TRIPS_CANCEL,
    PERMISSIONS.TRAVELERS_CREATE,
    PERMISSIONS.TRAVELERS_UPDATE,
    PERMISSIONS.TRAVELERS_MERGE,
    PERMISSIONS.HOTELS_CREATE,
    PERMISSIONS.HOTELS_UPDATE,
    PERMISSIONS.HOTELS_CANCEL,
    PERMISSIONS.TRANSFERS_CREATE,
    PERMISSIONS.TRANSFERS_UPDATE,
    PERMISSIONS.TRANSFERS_ASSIGN,
    PERMISSIONS.TRANSFERS_STATUS_UPDATE,
    PERMISSIONS.EXCURSIONS_CREATE,
    PERMISSIONS.EXCURSIONS_UPDATE,
    PERMISSIONS.VISAS_CREATE,
    PERMISSIONS.VISAS_UPDATE,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.MASTER_DATA_MANAGE,
    PERMISSIONS.DATA_QUALITY_READ,
    PERMISSIONS.DATA_QUALITY_RESOLVE,
    PERMISSIONS.IMPORTS_UPLOAD,
    PERMISSIONS.IMPORTS_REVIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.ATTACHMENTS_UPLOAD,
  ],
  RESERVATION_AGENT: [
    ...READ_ONLY,
    PERMISSIONS.TRIPS_CREATE,
    PERMISSIONS.TRIPS_UPDATE,
    PERMISSIONS.TRAVELERS_CREATE,
    PERMISSIONS.TRAVELERS_UPDATE,
    PERMISSIONS.HOTELS_CREATE,
    PERMISSIONS.HOTELS_UPDATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.ATTACHMENTS_UPLOAD,
  ],
  TRANSFER_COORDINATOR: [
    ...READ_ONLY,
    PERMISSIONS.TRANSFERS_CREATE,
    PERMISSIONS.TRANSFERS_UPDATE,
    PERMISSIONS.TRANSFERS_ASSIGN,
    PERMISSIONS.TRANSFERS_STATUS_UPDATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTACHMENTS_READ,
  ],
  EXCURSION_COORDINATOR: [
    ...READ_ONLY,
    PERMISSIONS.EXCURSIONS_CREATE,
    PERMISSIONS.EXCURSIONS_UPDATE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTACHMENTS_READ,
  ],
  VISA_AGENT: [
    ...READ_ONLY,
    PERMISSIONS.VISAS_CREATE,
    PERMISSIONS.VISAS_UPDATE,
    PERMISSIONS.VISAS_FINANCE_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.ATTACHMENTS_UPLOAD,
  ],
  FINANCE: [
    ...READ_ONLY,
    PERMISSIONS.VISAS_FINANCE_READ,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_DOCUMENTS_MANAGE,
    PERMISSIONS.FINANCE_PAYMENTS_CREATE,
    PERMISSIONS.FINANCE_PAYMENTS_REVERSE,
    PERMISSIONS.FINANCE_RECONCILE,
    PERMISSIONS.DATA_QUALITY_READ,
    PERMISSIONS.DATA_QUALITY_RESOLVE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.ATTACHMENTS_READ,
    PERMISSIONS.ATTACHMENTS_UPLOAD,
  ],
  VIEWER: READ_ONLY,
};

/** Read-only scopes an API key may be granted. Finance/admin are never default. */
export const API_KEY_SCOPES = {
  TRIPS_READ: 'trips:read',
  OPERATIONS_READ: 'operations:read',
  HOTELS_READ: 'hotels:read',
  TRANSFERS_READ: 'transfers:read',
  EXCURSIONS_READ: 'excursions:read',
  VISAS_READ: 'visas:read',
} as const;
export type ApiKeyScope = (typeof API_KEY_SCOPES)[keyof typeof API_KEY_SCOPES];
export const ALL_API_KEY_SCOPES = Object.values(API_KEY_SCOPES) as ApiKeyScope[];

/** Maps an API key scope onto the permissions it implies. */
export const API_KEY_SCOPE_PERMISSIONS: Record<ApiKeyScope, Permission[]> = {
  'trips:read': [PERMISSIONS.TRIPS_READ, PERMISSIONS.TRAVELERS_READ],
  'operations:read': [
    PERMISSIONS.TRIPS_READ,
    PERMISSIONS.HOTELS_READ,
    PERMISSIONS.TRANSFERS_READ,
    PERMISSIONS.EXCURSIONS_READ,
    PERMISSIONS.VISAS_READ,
  ],
  'hotels:read': [PERMISSIONS.HOTELS_READ],
  'transfers:read': [PERMISSIONS.TRANSFERS_READ],
  'excursions:read': [PERMISSIONS.EXCURSIONS_READ],
  'visas:read': [PERMISSIONS.VISAS_READ],
};
